package stubs

// DockerComposeTpl is the stub for the docker-compose.yml file generated by the
// bootstrap command
var composeYmlTpl = `
version: "2"

services:
  nginx:
    hostname: "nginx"
    domainname: "sievert.docker"
    container_name: "nginx"
    image: nginx:stable
    restart: always
    environment:
      POSTGRES_PASSWORD: 2adhXzQJ
      POSTGRES_USER: joinfinity
      POSTGRES_DB: joinfinity_canary_bd
networks:
  server:
    driver: none
  application:
    driver: bridge
  data:
    driver: bridge
`
